import type { Preset } from 'unocss'
import { presetIcons } from 'unocss'
import presetAnimations from 'unocss-preset-animations'
import { presetShadcnV3 } from 'unocss-preset-shadcn/v3'

export interface YfUiPresetOptions {
  color?: string
  radius?: number
  darkSelector?: string
}

/**
 * Presets required by @yf/ui.
 *
 * Consumer applications must add `presetWind3()` separately:
 *
 * ```ts
 * presets: [presetWind3(), ...presetYfUi()]
 * ```
 *
 * Icon collections resolve from `@iconify-json/*` packages installed in the
 * consumer dependency tree. Consumers must import the required Inter font CSS
 * themselves using side-effect imports.
 */
export function presetYfUi(options: YfUiPresetOptions = {}): Preset[] {
  const {
    color = 'zinc',
    radius = 0.5,
    darkSelector = '.dark',
  } = options

  /*
   * Chrome and Edge 109 do not support the oklch colors emitted by the current
   * preset, so this library deliberately uses the legacy hsl-based v3 preset.
   * The fixup also corrects chart and sidebar variable names generated by that
   * preset: --chart-1 through --chart-5 and --sidebar.
   */
  const fixupPreset: Preset = {
    name: '@yf/ui-fixup',
    preflights: [
      {
        getCSS: () => `:root {
  --success: 142 71% 35%;
  --success-foreground: 0 0% 98%;
  --warning: 48 96% 53%;
  --warning-foreground: 240 10% 4%;
}
html,
body {
  overscroll-behavior: none;
}
body {
  font-family: 'Inter', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif;
}`,
      },
    ],
    extendTheme: (theme) => {
      const t = theme as {
        colors?: Record<string, unknown>
        fontFamily?: Record<string, string>
      }
      t.colors ||= {}
      t.fontFamily ||= {}
      t.fontFamily.sans = "'Inter', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif"
      const colors = t.colors

      colors.success = {
        DEFAULT: 'hsl(var(--success))',
        foreground: 'hsl(var(--success-foreground))',
      }
      colors.warning = {
        DEFAULT: 'hsl(var(--warning))',
        foreground: 'hsl(var(--warning-foreground))',
      }

      for (let index = 1; index <= 5; index += 1) {
        const value = `hsl(var(--chart-${index}))`
        colors[`chart-${index}`] = value
        colors[`chart${index}`] = value
      }

      const sidebar = colors.sidebar
      if (sidebar && typeof sidebar === 'object' && !Array.isArray(sidebar)) {
        const sidebarColors = sidebar as Record<string, unknown>
        sidebarColors.DEFAULT = 'hsl(var(--sidebar))'
        sidebarColors.background = 'hsl(var(--sidebar))'
      }
      else {
        colors.sidebar = {
          DEFAULT: 'hsl(var(--sidebar))',
          background: 'hsl(var(--sidebar))',
        }
      }
    },
  }

  return [
    presetAnimations(),
    presetShadcnV3(
      { color, radius, darkSelector } as Parameters<typeof presetShadcnV3>[0],
      { componentLibrary: 'radix' },
    ),
    fixupPreset,
    presetIcons({
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ]
}

export const yfUiContent = ['node_modules/@yf/ui/dist/**/*.mjs']
